"""Build a reproducible, self-identifying submission bundle.

Why this is parameterised
-------------------------
We once could not tell which agent a ladder score belonged to (was 601 the heuristic
or the search agent?) because bundles were assembled by hand-copying files and editing
main.py. That cost a day of guessing. Now:

  * `--agent` picks the agent; the bundle is assembled from scratch every time
  * a MANIFEST.json goes inside the tarball, so a downloaded submission always says
    what it is (agent, git SHA, model hash, build time)
  * the bundle is validated before it can be shipped (extract, import, self-play,
    and assert the model actually LOADED -- a silent heuristic fallback would
    otherwise pass while shipping the wrong agent)

Usage:
    python make_submission.py --agent policy --model models/policy_rl_it12.npz --note "RL it12"
    python make_submission.py --agent heuristic --note "baseline"
    python make_submission.py --agent policy --no-validate     # skip the self-play check
"""
import argparse
import hashlib
import json
import os
import shutil
import stat
import subprocess
import sys
import tarfile
import tempfile
import time

ROOT = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.join(ROOT, "submission")
OUT = os.path.join(ROOT, "submission.tar.gz")

# agent -> (modules copied into the bundle, main.py import line, needs a model file)
AGENTS = {
    "heuristic": (["heuristic.py"], "from heuristic import make_agent", False),
    "policy": (["heuristic.py", "features.py", "policy_agent.py"],
               "from policy_agent import make_agent", True),
    "search": (["heuristic.py", "search_core.py", "search_agent.py", "opponent_model.py"],
               "from search_agent import make_agent", False),
}

MAIN_TEMPLATE = '''"""Kaggle entrypoint -- generated by make_submission.py. Do not edit by hand.

agent={agent}  built={built}  git={sha}
"""
import os

{import_line}


def read_deck_csv() -> list[int]:
    file_path = "deck.csv"
    if not os.path.exists(file_path):
        file_path = "/kaggle_simulations/agent/" + file_path
    with open(file_path) as f:
        lines = f.read().split("\\n")
    return [int(lines[i]) for i in range(60)]


_agent = make_agent(read_deck_csv())


def agent(obs_dict: dict) -> list[int]:
    return _agent(obs_dict)
'''


def git_sha() -> str:
    try:
        sha = subprocess.check_output(["git", "rev-parse", "--short", "HEAD"],
                                      cwd=ROOT, stderr=subprocess.DEVNULL).decode().strip()
        dirty = subprocess.call(["git", "diff", "--quiet"], cwd=ROOT,
                                stderr=subprocess.DEVNULL) != 0
        return sha + ("-dirty" if dirty else "")
    except Exception:
        return "unknown"


def sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()[:16]


def _rmtree(path: str):
    """Remove a tree despite read-only .pyc files and Windows/OneDrive file locks."""
    def onexc(func, p, exc):
        try:
            os.chmod(p, stat.S_IWRITE)
            func(p)
        except Exception:
            pass
    for _ in range(4):
        if not os.path.exists(path):
            return
        shutil.rmtree(path, onexc=onexc)
        if not os.path.exists(path):
            return
        time.sleep(0.4)   # a sync/AV handle may still be closing
    raise SystemExit(f"could not remove {path} — close anything holding it and retry")


def build(agent: str, model: str | None, deck_src: str, note: str) -> dict:
    modules, import_line, needs_model = AGENTS[agent]
    _rmtree(SRC)
    os.makedirs(SRC)

    # engine package
    shutil.copytree(os.path.join(ROOT, "cg"), os.path.join(SRC, "cg"),
                    ignore=shutil.ignore_patterns("__pycache__"))
    # agent modules (flat: the bundle has no `agents` package)
    for m in modules:
        shutil.copy(os.path.join(ROOT, "agents", m), os.path.join(SRC, m))
    # deck
    shutil.copy(deck_src, os.path.join(SRC, "deck.csv"))

    manifest = {
        "agent": agent,
        "note": note,
        "git": git_sha(),
        "built": time.strftime("%Y-%m-%d %H:%M:%S"),
        "deck": os.path.basename(deck_src),
    }

    if needs_model:
        if not model or not os.path.exists(model):
            raise SystemExit(f"--agent {agent} needs --model pointing at a .npz")
        shutil.copy(model, os.path.join(SRC, "policy.npz"))
        manifest["model"] = os.path.basename(model)
        manifest["model_sha256"] = sha256(model)

    with open(os.path.join(SRC, "main.py"), "w") as f:
        f.write(MAIN_TEMPLATE.format(agent=agent, built=manifest["built"],
                                     sha=manifest["git"], import_line=import_line))
    with open(os.path.join(SRC, "MANIFEST.json"), "w") as f:
        json.dump(manifest, f, indent=2)
    return manifest


def pack() -> float:
    if os.path.exists(OUT):
        os.remove(OUT)
    with tarfile.open(OUT, "w:gz") as tar:
        for name in sorted(os.listdir(SRC)):
            if name == "__pycache__":
                continue
            tar.add(os.path.join(SRC, name), arcname=name,
                    filter=lambda ti: None if "__pycache__" in ti.name else ti)
    return os.path.getsize(OUT) / (1024 * 1024)


def validate(expect_model: bool) -> str:
    """Extract to a clean dir and play a real self-play game, as Kaggle does."""
    tmp = tempfile.mkdtemp(prefix="valsub_")
    with tarfile.open(OUT) as t:
        t.extractall(tmp)
    for req in ("main.py", "deck.csv", "MANIFEST.json"):
        if not os.path.exists(os.path.join(tmp, req)):
            raise SystemExit(f"bundle missing {req}")

    code = r'''
import os, sys, time, json
sys.path.insert(0, sys.argv[1]); os.chdir(sys.argv[1])
import main
deck = main.agent({"select": None, "logs": [], "current": None})
assert len(deck) == 60, "deck.csv did not yield 60 cards"
if sys.argv[2] == "1":
    import policy_agent
    pa = policy_agent.PolicyAgent(main.read_deck_csv())
    assert pa.net is not None, "MODEL DID NOT LOAD -> would silently ship the heuristic"
from cg.game import battle_start, battle_select, battle_finish
obs, sd = battle_start(deck, deck)
assert obs is not None, f"battle_start failed errorType={sd.errorType}"
steps = 0; worst = 0.0
while obs["current"]["result"] == -1:
    t = time.perf_counter(); sel = main.agent(obs); worst = max(worst, time.perf_counter()-t)
    obs = battle_select(sel); steps += 1
    if steps > 5000: raise SystemExit("game did not terminate")
battle_finish()
print(json.dumps({"steps": steps, "result": obs["current"]["result"],
                  "worst_ms": round(worst*1000, 1)}))
'''
    p = subprocess.run([sys.executable, "-X", "utf8", "-c", code, tmp,
                        "1" if expect_model else "0"],
                       capture_output=True, text=True)
    if p.returncode != 0:
        raise SystemExit(f"VALIDATION FAILED:\n{p.stdout}\n{p.stderr}")
    return p.stdout.strip().splitlines()[-1]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--agent", choices=sorted(AGENTS), default="policy")
    ap.add_argument("--model", default="models/policy_rl_it12.npz",
                    help="weights for --agent policy")
    ap.add_argument("--deck", default="decks/deck.csv",
                    help="deck.csv to ship (falls back to the generated Lucario list)")
    ap.add_argument("--note", default="", help="free text recorded in MANIFEST.json")
    ap.add_argument("--no-validate", action="store_true")
    args = ap.parse_args()

    deck_src = args.deck
    if not os.path.exists(deck_src):
        # regenerate from the deck module so the bundle is never stale
        sys.path.insert(0, ROOT)
        from decks.mega_lucario import DECK
        os.makedirs(os.path.dirname(deck_src) or ".", exist_ok=True)
        with open(deck_src, "w") as f:
            f.write("\n".join(str(c) for c in DECK) + "\n")

    man = build(args.agent, args.model, deck_src, args.note)
    mb = pack()
    print(json.dumps(man, indent=2))
    if not args.no_validate:
        print("validation:", validate(expect_model=AGENTS[args.agent][2]))
    print(f"wrote submission.tar.gz ({mb:.1f} MiB, limit 197.7)")
    print("Record it:  python log_submission.py --agent %s --note %r" % (args.agent, args.note))


if __name__ == "__main__":
    main()
